### ISSUE TITLE
GLabel throws NoSuchMethodError caling getFont with Processing 2.0b1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [roloww/gui4processing#9]
```
What steps will reproduce the problem?
1. Create a sketch with a GLabel
2. Run it
3. See error

What is the expected output? What do you see instead?

Should see a window with a label, but instead get this error:



Exception in thread "Animation Thread" java.lang.NoSuchMethodError: 
processing.core.PFont.getFont()Ljava/awt/Font;
    at guicomponents.GLabel.labelCoreCtor(Unknown Source)
    at guicomponents.GLabel.<init>(Unknown Source)


What version of the product are you using? On what operating system?

Processing 2.0b1 on Windows 7 32-bit, also Processing 2.0b1 on Ubuntu  10.10.

Please provide any additional information below.

Processing 2.0b1 is what is currently the default download on Processing.org.
```

Original issue reported on code.google.com by `james.br...@gmail.com` on 7 Sep 2012 at 11:15

**Comment by GoogleCodeExporter** [comment]
```
The PFont.getFont() method was removed somewhere between 2.0a6 and 2.0b1

G4P V2.02 has resolved this issue
```

Original comment by `p.k.la...@gmail.com` on 8 Sep 2012 at 2:17
- Changed state: **Fixed**
